# Example of PCA using the correlation matrix

Author: Edrei Santos

In [ ]:
# Importing data and libraries
import numpy as np
import polars as pl

data = pl.read_excel("dados_brutos_cap3_mingoti.xlsx")
data = data.drop(data.columns[0])
data = data.to_numpy()

print(data)

[[ 9893   564 17689]
 [ 8776   389 17359]
 [13572  1103 18597]
 [ 6455   743  8745]
 [ 5129   203 14397]
 [ 5432   215  3467]
 [ 3807   385  4679]
 [ 3423   187  6754]
 [ 3708   127  2275]
 [ 3294   297  6754]
 [ 5433   432  5589]
 [ 6287   451  8972]]
